Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 12, in <module>
    from tappsi_api.serializers import UserSerializer, RideSerializer, DriverSerializer
  File "c:\Users\Junior\tappsi_test\tappsi_api\serializers.py", line 13, in <module>
    from rest_framework.pagination import PaginationSerializer
ImportError: cannot import name PaginationSerializer
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 12, in <module>
    from tappsi_api.serializers import UserSerializer, RideSerializer, DriverSerializer
  File "c:\Users\Junior\tappsi_test\tappsi_api\serializers.py", line 13, in <module>
    from rest_framework.pagination import PaginationSerializer
ImportError: cannot import name PaginationSerializer
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 12, in <module>
    from tappsi_api.serializers import UserSerializer, RideSerializer, DriverSerializer
  File "c:\Users\Junior\tappsi_test\tappsi_api\serializers.py", line 62, in <module>
    class PaginatedDriverSerializer(PaginationSerializer):
NameError: name 'PaginationSerializer' is not defined
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 12, in <module>
    from tappsi_api.serializers import UserSerializer, RideSerializer, DriverSerializer
  File "c:\Users\Junior\tappsi_test\tappsi_api\serializers.py", line 62, in <module>
    class PaginatedDriverSerializer(pagination.PaginationSerializer):
AttributeError: 'module' object has no attribute 'PaginationSerializer'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 64, in <module>
    class AvailableView(generics.ListAPIView):
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 68, in AvailableView
    pagination_class =StandardResultsSetPagination
NameError: name 'StandardResultsSetPagination' is not defined
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 64, in <module>
    class AvailableView(generics.ListAPIView):
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 68, in AvailableView
    pagination_class =StandardResultsSetPagination
NameError: name 'StandardResultsSetPagination' is not defined
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 16, in <module>
    from rest_framework.response import Response, HttpResponse
ImportError: cannot import name HttpResponse
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 16, in <module>
    from rest_framework.response import Response, HttpResponse
ImportError: cannot import name HttpResponse
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 25, in <module>
    from django import HttpResponse
ImportError: cannot import name HttpResponse
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 72
    print "masssssssssssssssssss"""
    ^
IndentationError: unexpected indent
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 74
    print "SISISISI"
        ^
IndentationError: expected an indented block
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 453, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 373, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
Internal Server Error: /
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 83
    """
    ^
IndentationError: unexpected indent
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 87, in get_response
    response = middleware_method(request)
  File "c:\Python27\lib\site-packages\django\middleware\common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 614, in is_valid_path
    resolve(path, urlconf)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 489, in resolve
    return get_resolver(urlconf).resolve(path)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 83
    """
    ^
IndentationError: unexpected indent
Not Found: /
Not Found: /favicon.ico
Forbidden (Permission denied): /api/v1/docs/
Not Found: /api/docs/
Forbidden (Permission denied): /api/docs/
Forbidden (Permission denied): /docs/
Not Found: /api/v1/docs/
Not Found: /api/v1/docs/
Not Found: /api/v1/docs/
Not Found: /api/v1/docs/
Not Found: /
Not Found: /api/v1/docs/
Not Found: /api/v1/docs/
Not Found: /api/v1/docs/
Not Found: /v1/api/docs/
Not Found: /api/v1/docs/
Not Found: /api-docs/
Not Found: /api-docs/
Not Found: /api-docs/
Not Found: /api-docs/
Not Found: /api-docs/
Not Found: /api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/docs//api-docs/api/v1/availables
Not Found: /api/v1/docs//api-docs/api/v1/rides
Not Found: /api/v1/docs//api-docs/api/v1/users
Not Found: /api/v1/api-docs
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/docs/
Not Found: /api-docs/
Not Found: /api-docs/
Not Found: /api/v1/api-docs/
Not Found: /api/v1/api-docs/
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 26, in <module>
    from rest_framework_yaml.parsers import YAMLParser
ImportError: No module named rest_framework_yaml.parsers
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 13, in <module>
    from rest_framework import viewsets, mixins, permissions, renderers, status, generics
  File "c:\Python27\lib\site-packages\rest_framework\viewsets.py", line 24, in <module>
    from rest_framework import views, generics, mixins
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 90, in <module>
    class APIView(View):
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 93, in APIView
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES
  File "c:\Python27\lib\site-packages\rest_framework\settings.py", line 206, in __getattr__
    val = perform_import(val, attr)
  File "c:\Python27\lib\site-packages\rest_framework\settings.py", line 158, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "c:\Python27\lib\site-packages\rest_framework\settings.py", line 174, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework_yaml.parsers.YAMLParser' for API setting 'DEFAULT_RENDERER_CLASSES'. ImportError: No module named rest_framework_yaml.parsers.
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 29, in <module>
    url(r'^api/v1/docs/', include('rest_framework_swagger.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Python27\lib\site-packages\rest_framework_swagger\urls.py", line 3, in <module>
    from rest_framework_swagger.views import SwaggerResourcesView, SwaggerApiView, SwaggerUIView
  File "c:\Python27\lib\site-packages\rest_framework_swagger\views.py", line 25, in <module>
    api_settings.DEFAULT_RENDERER_CLASSES,
  File "c:\Python27\lib\site-packages\rest_framework_swagger\views.py", line 24, in <lambda>
    lambda item: item.format == 'json',
AttributeError: type object 'YAMLParser' has no attribute 'format'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 29, in <module>
    url(r'^api/v1/docs/', include('rest_framework_swagger.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Python27\lib\site-packages\rest_framework_swagger\urls.py", line 3, in <module>
    from rest_framework_swagger.views import SwaggerResourcesView, SwaggerApiView, SwaggerUIView
  File "c:\Python27\lib\site-packages\rest_framework_swagger\views.py", line 25, in <module>
    api_settings.DEFAULT_RENDERER_CLASSES,
  File "c:\Python27\lib\site-packages\rest_framework_swagger\views.py", line 24, in <lambda>
    lambda item: item.format == 'json',
AttributeError: type object 'YAMLParser' has no attribute 'format'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 29, in <module>
    url(r'^api/v1/docs/', include('rest_framework_swagger.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Python27\lib\site-packages\rest_framework_swagger\urls.py", line 3, in <module>
    from rest_framework_swagger.views import SwaggerResourcesView, SwaggerApiView, SwaggerUIView
  File "c:\Python27\lib\site-packages\rest_framework_swagger\views.py", line 25, in <module>
    api_settings.DEFAULT_RENDERER_CLASSES,
  File "c:\Python27\lib\site-packages\rest_framework_swagger\views.py", line 24, in <lambda>
    lambda item: item.format == 'json',
AttributeError: type object 'YAMLParser' has no attribute 'format'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework_yaml\renderers.py", line 39, in render
    default_flow_style=self.default_flow_style
  File "c:\Python27\lib\site-packages\yaml\__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "c:\Python27\lib\site-packages\yaml\__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 28, in represent
    node = self.represent_data(data)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "c:\Python27\lib\site-packages\rest_framework_yaml\encoders.py", line 36, in represent_mapping
    node_value = self.represent_data(item_value)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: global name 'data' is not defined
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework_yaml\renderers.py", line 39, in render
    default_flow_style=self.default_flow_style
  File "c:\Python27\lib\site-packages\yaml\__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "c:\Python27\lib\site-packages\yaml\__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 28, in represent
    node = self.represent_data(data)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "c:\Python27\lib\site-packages\yaml\representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: [<Driver: Driver object>, <Driver: Driver object>, <Driver: Driver object>, <Driver: Driver object>]
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 99, in render
    separators=separators
  File "c:\Python27\lib\json\__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "c:\Python27\lib\site-packages\rest_framework\utils\encoders.py", line 61, in default
    return super(JSONEncoder, self).default(obj)
  File "c:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: NameError("global name 'data' is not defined",) is not JSON serializable
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 439, in dispatch
    self.initial(request, *args, **kwargs)
TypeError: initial() takes no arguments (2 given)
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 439, in dispatch
    self.initial(request, *args, **kwargs)
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 73, in initial
    print "parser_classes:"+parser_classes
NameError: global name 'parser_classes' is not defined
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 439, in dispatch
    self.initial(request, *args, **kwargs)
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 73, in initial
    print "parser_classes:"+self.parser_classes
TypeError: cannot concatenate 'str' and 'tuple' objects
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 439, in dispatch
    self.initial(request, *args, **kwargs)
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 73, in initial
    print "parser_classes:".self.parser_classes
AttributeError: 'str' object has no attribute 'self'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 439, in dispatch
    self.initial(request, *args, **kwargs)
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 74, in initial
    self.parser_classes=(JSONParser,)
NameError: global name 'JSONParser' is not defined
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 439, in dispatch
    self.initial(request, *args, **kwargs)
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 74, in initial
    self.parser_classes=(JSONParser,)
NameError: global name 'JSONParser' is not defined
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 28, in <module>
    from rest_framework.parsers import JSONParser, TemplateHTMLParse
ImportError: cannot import name TemplateHTMLParse
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 28, in <module>
    from rest_framework.parsers import JSONParser, TemplateHTMLParser
ImportError: cannot import name TemplateHTMLParser
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 194, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: template.html
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 194, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: tappsi_api/templates/template.html
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 194, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: templates/template.html
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 188, in select_template
    return get_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\defaulttags.py", line 824, in do_for
    " 'for x in y': %s" % token.contents)
TemplateSyntaxError: 'for' statements should use the format 'for x in y': for i in [2, 2, 1]
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 188, in select_template
    return get_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\defaulttags.py", line 824, in do_for
    " 'for x in y': %s" % token.contents)
TemplateSyntaxError: 'for' statements should use the format 'for x in y': for i in [2, 2, 1]:
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 188, in select_template
    return get_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\defaulttags.py", line 832, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "c:\Python27\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ':' from 'obj:'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 188, in select_template
    return get_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\loader_tags.py", line 175, in do_block
    nodelist = parser.parse(('endblock',))
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\defaulttags.py", line 832, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "c:\Python27\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ':' from 'obj:'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 188, in select_template
    return get_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\loader_tags.py", line 175, in do_block
    nodelist = parser.parse(('endblock',))
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\defaulttags.py", line 832, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "c:\Python27\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '(1,2,3):' from 'range(1,2,3):'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 164, in render
    template = self.resolve_template(template_names)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 188, in select_template
    return get_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\loader_tags.py", line 175, in do_block
    nodelist = parser.parse(('endblock',))
  File "c:\Python27\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "c:\Python27\lib\site-packages\django\template\defaulttags.py", line 832, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "c:\Python27\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "c:\Python27\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '[1,2,3]:' from 'range[1,2,3]:'
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 96
    return Response('data'=serializer.data, template_name='template.html')
SyntaxError: keyword can't be an expression
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 96
    return Response('data'=drivers, template_name='template.html')
SyntaxError: keyword can't be an expression
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 96
    return Response({'data'=drivers}, template_name='template.html')
                           ^
SyntaxError: invalid syntax
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Users\Junior\tappsi_test\tappsi_test\urls.py", line 11, in <module>
    from tappsi_api.views import UserViewSet, RideViewSet, AvailableView
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 96
    return Response({'data'=drivers}, template_name='template.html')
                           ^
SyntaxError: invalid syntax
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 163, in render
    template_names = self.get_template_names(response, view)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 187, in get_template_names
    'Returned a template response with no `template_name` attribute set on either the view or response'
ImproperlyConfigured: Returned a template response with no `template_name` attribute set on either the view or response
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 137, in get_response
    response = response.render()
  File "c:\Python27\lib\site-packages\django\template\response.py", line 103, in render
    self.content = self.rendered_content
  File "c:\Python27\lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 163, in render
    template_names = self.get_template_names(response, view)
  File "c:\Python27\lib\site-packages\rest_framework\renderers.py", line 187, in get_template_names
    'Returned a template response with no `template_name` attribute set on either the view or response'
ImproperlyConfigured: Returned a template response with no `template_name` attribute set on either the view or response
Internal Server Error: /api/v1/availables/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "c:\Python27\lib\site-packages\rest_framework\views.py", line 439, in dispatch
    self.initial(request, *args, **kwargs)
  File "c:\Users\Junior\tappsi_test\tappsi_api\views.py", line 82, in initial
    self.parser_classes=(XMLParser,)
NameError: global name 'XMLParser' is not defined
